WURL = "PUBLIC COINMARKETCAP WATCHLIST URL"
MROOM = "MATRIX ROOM ID (REPLACE ! WITH %21)"
MTOKEN = "MATRIX ACCESS TOKEN"
MSERVER = "MATRIX SERVER HOST"
IMPORTANT_COINS = [
                    "bitcoin-cash",
                    "monero",
]
